// Program and Department mappings
export const programs = ["BT", "BS", "BTM", "BSM", "DoubleMajor", "DualA", "DualB", "DualC", "MT", "MSR", "MSc", "MDes", "MBA", "PhD"];

export const departments = [
  "AE", "BSBE", "CE", "CHE", "CSE", "EE", "MSE", "ME", "CHM", "ECO", "ES", "MTH", 
  "SDS", "PHY", "CGS", "DES", "MS", "MSP", "NET", "PSE", "Stats", "HSS", 
  "Mathematics", "SEE", "SPASE", "AEUAS"
];

// ID to Branch mapping (program_department_id -> "Program-Department")
export const idToBranch: Record<number, string> = {
  1: "BT-AE",
  2: "BT-BSBE",
  3: "BT-CE",
  4: "BT-CHE",
  5: "BT-CSE",
  6: "BT-EE",
  7: "BT-MSE",
  8: "BT-ME",
  9: "BS-CHM",
  10: "BS-ECO",
  11: "BS-ES",
  12: "BS-MTH",
  13: "BS-PHY",
  14: "MT-AE",
  15: "MT-BSBE",
  16: "MT-CE",
  17: "MT-CHE",
  18: "MT-CSE",
  19: "MT-EE",
  20: "MT-MSE",
  21: "MT-ME",
  22: "MT-ES",
  23: "MT-MS",
  24: "MT-MSP",
  25: "MT-NET",
  26: "MT-PSE",
  27: "MT-SEE",
  28: "DoubleMajor-AE",
  29: "DoubleMajor-BSBE",
  30: "DoubleMajor-CE",
  31: "DoubleMajor-CHE",
  32: "DoubleMajor-CSE",
  33: "DoubleMajor-EE",
  34: "DoubleMajor-MSE",
  35: "DoubleMajor-ME",
  36: "DoubleMajor-ECO",
  37: "DoubleMajor-MTH",
  38: "DualA-AE",
  39: "DualA-BSBE",
  40: "DualA-CE",
  41: "DualA-CHE",
  42: "DualA-CSE",
  43: "DualA-EE",
  44: "DualA-MSE",
  45: "DualA-CHM",
  46: "DualA-ECO",
  47: "DualA-MTH",
  48: "DualA-PHY",
  49: "DualB-AE",
  50: "DualB-BSBE",
  51: "DualB-CE",
  52: "DualB-CHE",
  53: "DualB-CSE",
  54: "DualB-EE",
  55: "DualB-MSE",
  56: "DualB-ECO",
  57: "DualB-PHY",
  58: "DualB-DES",
  59: "DualC-EE",
  60: "DualC-MS",
  61: "MDes-DES",
  62: "MBA-MS",
  63: "PhD-AE",
  64: "PhD-BSBE",
  65: "PhD-CE",
  66: "PhD-CHE",
  67: "PhD-CSE",
  68: "PhD-EE",
  69: "PhD-MSE",
  70: "PhD-ME",
  71: "PhD-ES",
  72: "PhD-MTH",
  73: "PhD-PHY",
  74: "PhD-CGS",
  75: "PhD-DES",
  76: "PhD-MS",
  77: "PhD-NET",
  78: "PhD-PSE",
  79: "PhD-Stats",
  80: "PhD-HSS",
  81: "PhD-Mathematics",
  82: "PhD-SPASE",
  83: "MSc-Stats",
  84: "MSc-MTH",
  85: "MSR-AE",
  86: "MSR-CE",
  87: "MSR-CHE",
  88: "MSR-CSE",
  89: "MSR-EE",
  90: "MSR-ME",
  91: "MSR-CGS",
  93: "MSR-PSE",
  95: "BS-SDS",
  96: "DoubleMajor-CHM",
  97: "DoubleMajor-SDS",
  98: "DoubleMajor-PHY",
  99: "DualA-ME",
  100: "DualA-SDS",
  101: "DualB-ME",
  102: "DualB-MTH",
  103: "DualB-SDS",
  104: "DualB-MS",
  106: "MT-SEE",
  107: "MSc-CHM",
  108: "MSc-ECO",
  109: "MSc-ES",
  110: "MSc-PHY",
  111: "PhD-CHM",
  112: "PhD-ECO",
  113: "PhD-MSP",
  115: "DualA-ES",
  116: "DualB-ES",
  117: "MT-CGS",
  119: "BTM-AE",
  120: "BTM-BSBE",
  121: "BTM-CE",
  122: "BTM-CHE",
  123: "BTM-CSE",
  124: "BTM-EE",
  125: "BTM-MSE",
  126: "BTM-ME",
  127: "BSM-CHM",
  128: "BSM-ECO",
  129: "BSM-ES",
  130: "BSM-MTH",
  131: "BSM-SDS",
  132: "BSM-PHY",
  200: "NA"
};

export function getBranchName(programDeptId: number): string {
  if (programDeptId === 200 || programDeptId === 0) return "NA";
  return idToBranch[programDeptId] || "Unknown";
}
